version: "3.8"

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "Example Org"
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_ADMIN_PASSWORD: "admin1234"
      LDAP_BACKEND: "mdb"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    ports:
      - "389:389"   # LDAP port
      - "636:636"   # LDAPS port
    networks:
      - ldap-net

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
    ports:
      - "8081:80"
    depends_on:
      - openldap
    networks:
      - ldap-net

networks:
  ldap-net:
    driver: bridge

volumes:
  ldap_data:
    name: ldap_data  # Forces the exact name
  ldap_config:
    name: ldap_config